language: python
python:
        - 2.7

before_install:
  # update pip
  - pip install -q --upgrade pip

  # build and install numpy first
  - pip install -q "numpy>=1.7"

  # install cython to speed up scipy build
  - travis_retry pip install -q --install-option="--no-cython-compile" Cython

  # install testing dependencies
  - pip install -q coveralls "pytest>=2.8" unittest2

install:
        - pip install -r requirements.txt
        - python setup.py build
script:
        - coverage run --source=sbms setup.py test
        - pip install . -vvv

after_success:
        - coveralls
